spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/capstone
      username: root
      password: 1234
      connection-timeout: 10000
      maximum-pool-size: 10
      max-lifetime: 60000
      minimum-idle: 5
